import { InputData } from './types';
import { toSlug } from './utils';

const inputData: InputData = {
  posts: [
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-1)',
      slug: toSlug('webdesign layout A-1'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign01',
      images: 'webdesign01.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-2)',
      slug: toSlug('webdesign layout A-2'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign02',
      images: 'webdesign02.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-3)',
      slug: toSlug('webdesign layout A-3'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign03',
      images: 'webdesign03.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-4)',
      slug: toSlug('webdesign layout A-4'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign04',
      images: 'webdesign04.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 A유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-1)',
      slug: toSlug('webdesign layout B-1'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign05',
      images: 'webdesign05.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-2)',
      slug: toSlug('webdesign layout B-2'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign06',
      images: 'webdesign06.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-3)',
      slug: toSlug('webdesign layout B-3'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign07',
      images: 'webdesign07.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-4)',
      slug: toSlug('webdesign layout B-4'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign08',
      images: 'webdesign08.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 B유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-1)',
      slug: toSlug('webdesign layout C-1'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign09',
      images: 'webdesign09.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-2)',
      slug: toSlug('webdesign layout C-2'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign10',
      images: 'webdesign10.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-3)',
      slug: toSlug('webdesign layout C-3'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign11',
      images: 'webdesign11.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-4)',
      slug: toSlug('webdesign layout C-4'),
      category: 'lecture',
      subCategory: 'webdesign',
      components: 'webdesign12',
      images: 'webdesign12.jpg',
      tags: ['webdesign', 'layout'],
      description: '웹디자인개발기능사 레이아웃 C유형 연습 강의입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },

    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:변수',
      slug: toSlug('react javascript class1'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript01',
      images: 'javascript01.jpg',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:배열',
      slug: toSlug('react javascript class2'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript02',
      images: 'javascript02.jpg',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:객체',
      slug: toSlug('react javascript class3'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript03',
      images: 'javascript03.jpg',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
    {
      title: '리액트를 위한, 자바스크립트 기초 클래스 - 데이터 저장하기:객체',
      slug: toSlug('react javascript class4'),
      category: 'lecture',
      subCategory: 'javascript',
      components: 'javascript04',
      images: 'javascript04.jpg',
      tags: ['javascript'],
      description:
        '리액트를 위한, 자바스크립트 기초 클래스 데이터 저장하기 파트입니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
    },
  ],
};

export default inputData;
